export const projectsData = {
  productDesign: [
    {
      id: 10,
      title: "Naija Diaspora Hub",
      category: "Product Design",
      image: "/projects/ndh-case-study/cover.webp",
      color: "#1B7940",
      description: "A verified digital marketplace bridging the trust gap for global Nigerians.",
      tags: ["UI/UX", "Case Study", "Marketplace"],
      link: "/projects/naija-diaspora-hub",
    },
    {
      id: 4,
      title: "Finddr App Design",
      category: "Product Design",
      image: "/projects/finddr.webp",
      color: "#22b022",
      description: "A mobile app created to help find artisans to work with.",
      tags: ["UI/UX", "Mobile Design", "Healthcare"],
      link: "/projects/finddr",
    },
    {
      id: 5,
      title: "True North App Design",
      category: "Product Design",
      image: "/projects/true-north.webp",
      color: "#b07022",
      description: "A game design for a mobile app.",
      tags: ["App Design", "Game Design", "User Interface"],
      link: "/projects/true-north",
    },
    {
      id: 6,
      title: "Ecommerce Dashboard",
      category: "Product Design",
      image: "/projects/ecommerce.webp",
      color: "#2270b0",
      description: "A dashboard for an ecommerce platform.",
      tags: ["UI/UX", "Dashboard Design", "Ecommerce"],
      link: "/projects/ecommerce",
    },
  ],
  webDevelopment: [
    {
      id: 7,
      title: "Financial Tracking App",
      category: "Web Development",
      image: "/projects/numero.webp",
      color: "#b0b022",
      description: "A financial tracking app for tracking personal finances.",
      tags: ["Next.js", "E-commerce", "Full Stack"],
      link: "https://numero-theta-dusky.vercel.app/",
    },
    {
      id: 8,
      title: "Naija Diaspora Hub",
      category: "Web Development",
      image: "/projects/ndh-case-study/cover.webp",
      color: "#1B7940",
      description: "A platform for Nigerians to connect with their diaspora.",
      tags: ["Next.js", "E-commerce", "Full Stack"],
      link: "https://naija-diaspora-hub.vercel.app/",
    },
    {
      id: 9,
      title: "Brinova",
      category: "Web Development",
      image: "/projects/Brinova.webp",
      color: "#4A90D9",
      description: "A modern web application built with cutting-edge technologies.",
      tags: ["Next.js", "Web App", "Full Stack"],
      link: "https://brinova-eight.vercel.app",
    },
  ],
  brandDesign: [
    {
      id: 1,
      title: "Organ Station Brand Identity",
      category: "Brand Design",
      image: "/projects/organstation.webp",
      color: "#F8804F",
      description:
        "A Branding project for a new startup in the health industry",
      tags: ["Branding", "Visual Identity", "Logo Design"],
      link: "/projects/organstation",
    },
    {
      id: 2,
      title: "Web Kitchen Brand Design",
      category: "Brand Design",
      image: "/projects/WK1.webp",
      color: "#184B6A",
      description: "A brand design for a creative tech studio",
      tags: ["Tech Branding", "Logo Design", "Visual Identity"],
      link: "/projects/web-kitchen",
    },
    {
      id: 3,
      title: "Jedidah Brand Design",
      category: "Brand Design",
      image: "/projects/jedidah.webp",
      color: "#b022b0",
      description: "A popular clothing brand bringing life to streetwear",
      tags: ["Streetwear", "Visual Identity", "Logo Design"],
      link: "/projects/jedidah",
    },
  ],
};
