export const projectsData = {
  brandDesign: [
    {
      id: 1,
      title: "Organ Station Brand Identity",
      category: "Brand Design",
      image: "projects/organstation.png",
      color: "#F8804F",
      description:
        "A Branding project for a new startup in the health industry",
      tags: ["Branding", "Visual Identity", "Logo Design"],
      link: "/projects/organstation",
    },
    {
      id: 2,
      title: "Web Kitchen Brand Design",
      category: "Brand Design",
      image: "projects/WK1.png",
      color: "#184B6A",
      description: "A brand design for a creative tech studio",
      tags: ["Tech Branding", "Logo Design", "Visual Identity"],
      link: "/projects/web-kitchen",
    },
    {
      id: 3,
      title: "Jedidah Brand Design",
      category: "Brand Design",
      image: "projects/jedidah.png",
      color: "#b022b0",
      description: "A popular clothing brand bringing life to streetwear",
      tags: ["Streetwear", "Visual Identity", "Logo Design"],
      link: "/projects/jedidah",
    },
  ],
  productDesign: [
    {
      id: 4,
      title: "Finddr App Design",
      category: "Product Design",
      image: "projects/finddr.png",
      color: "#22b022",
      description: "A mobile app created to help find artisans to work with.",
      tags: ["UI/UX", "Mobile Design", "Healthcare"],
      link: "/projects/finddr",
    },
    {
      id: 5,
      title: "True North App Design",
      category: "Product Design",
      image: "projects/true-north.png",
      color: "#b07022",
      description: "A game design for a mobile app.",
      tags: ["App Design", "Game Design", "User Interface"],
      link: "/projects/true-north",
    },
    {
      id: 6,
      title: "Ecommerce Dashboard",
      category: "Product Design",
      image: "projects/ecommerce.png",
      color: "#2270b0",
      description: "A dashboard for an ecommerce platform.",
      tags: ["UI/UX", "Dashboard Design", "Ecommerce"],
      link: "/projects/ecommerce",
    },
  ],
  webDevelopment: [
    {
      id: 7,
      title: "Financial Tracking App",
      category: "Web Development",
      image: "product1.png",
      color: "#b0b022",
      description: "A financial tracking app for tracking personal finances.",
      tags: ["Next.js", "E-commerce", "Full Stack"],
      link: "https://numero-theta-dusky.vercel.app/",
    },
    // {
    //   id: 8,
    //   title: "Educational Platform",
    //   category: "Web Development",
    //   image: "product2.png",
    //   color: "#5022b0",
    //   description: "Interactive learning environment with advanced features.",
    //   tags: ["React", "EdTech", "Interactive"],
    //   link: "/projects/web-kitchen",
    // },
    // {
    //   id: 9,
    //   title: "Real Estate Listing Portal",
    //   category: "Web Development",
    //   image: "product3.png",
    //   color: "#b05022",
    //   description: "Property search and management system with 3D tours.",
    //   tags: ["Three.js", "Tailwind", "Property Tech"],
    //   link: "/projects/web-kitchen",
    // },
  ],
};
