export const projectsData = {
  productDesign: [
    {
      id: 11,
      title: "Nova: High-Performance Crypto Ops",
      category: "Product Design",
      image: "/projects/nova-trade-case-study/cover.png",
      color: "#8A2BE2",
      description: "Engineering a high-frequency trading command center with real-time liquidity listeners and anti-bot filters.",
      tags: ["Design Engineering", "DeFi", "Real-time Ops"],
      link: "/projects/nova-trade-case-study",
    },
    {
      id: 10,
      title: "Naija Diaspora Hub (Global Architecture)",
      category: "Product Design",
      image: "/projects/ndh-case-study/cover.webp",
      color: "#1B7940",
      description: "Solving the $5.4B trust gap for the Nigerian diaspora through an autonomous vendor verification engine.",
      tags: ["Marketplace Architecture", "Trust Engine", "Security"],
      link: "/projects/naija-diaspora-hub",
    },
    {
      id: 4,
      title: "Finddr: Service Fulfillment Logic",
      category: "Product Design",
      image: "/projects/finddr.webp",
      color: "#22b022",
      description: "Redesigning the marketplace matching logic to increase artisan conversion by 40% using predictive UX.",
      tags: ["UX Engineering", "Conversion Strategy"],
      link: "/projects/finddr",
    },
    {
      id: 5,
      title: "True North: Engagement Engineering",
      category: "Product Design",
      image: "/projects/true-north.webp",
      color: "#b07022",
      description: "Building immersive interaction loops designed to maximize user retention and session duration.",
      tags: ["Interaction Design", "Retention Ops"],
      link: "/projects/true-north",
    },
    {
      id: 6,
      title: "SaaS Ops Dashboard",
      category: "Product Design",
      image: "/projects/ecommerce.webp",
      color: "#2270b0",
      description: "Converting complex commerce data into actionable revenue signals for high-scale retail operations.",
      tags: ["Data Engineering", "Revenue UX", "SaaS"],
      link: "/projects/ecommerce",
    },
  ],
  webDevelopment: [
    {
      id: 12,
      title: "Flux: Multi-Tenant Enterprise OS",
      category: "Web Development",
      image: "/projects/flux.svg",
      color: "#4f46e5",
      description: "A high-performance project orchestration system built for elite teams needing uncompromised throughput.",
      tags: ["Next.js", "Enterprise Architecture", "SaaS"],
      link: "https://www.fluxboard.site",
    },
    {
      id: 7,
      title: "Capital Tracking & Analysis Engine",
      category: "Web Development",
      image: "/projects/numero.png",
      color: "#b0b022",
      description: "Developing robust financial infrastructure for automated capital tracking and predictive spend analysis.",
      tags: ["Fintech", "Full-Stack Engineering"],
      link: "https://numero-finance.vercel.app/",
    },
    {
      id: 8,
      title: "NDH Infrastructure Deployment",
      category: "Web Development",
      image: "/projects/ndh-case-study/cover.webp",
      color: "#1B7940",
      description: "Architecting the full-stack bridge for a global Nigerian trade network with high-security vendor onboarding.",
      tags: ["System Architecture", "Global Scale"],
      link: "https://www.naijadiasporahub.com",
    },
    {
      id: 9,
      title: "Brinova: High-Traffic Media Engine",
      category: "Web Development",
      image: "/projects/Brinova.webp",
      color: "#4A90D9",
      description: "Engineering a scalable content delivery network focused on sub-second latency for visual media assets.",
      tags: ["CDN Ops", "Performance Engineering"],
      link: "https://www.brinovamedia.com",
    },
  ],
  brandDesign: [
    {
      id: 1,
      title: "Organ Station: Identity for Scale",
      category: "Brand Design",
      image: "/projects/organstation.webp",
      color: "#F8804F",
      description:
        "Developing a trust-centric visual language for a healthcare disruptor preparing for international expansion.",
      tags: ["Identity Systems", "Strategic Branding"],
      link: "/projects/organstation",
    },
    {
      id: 2,
      title: "Web Kitchen: Visual Strategy",
      category: "Brand Design",
      image: "/projects/WK1.webp",
      color: "#184B6A",
      description: "Creating a high-performance visual core for a creative technology studio focused on premium client acquisition.",
      tags: ["Visual Strategy", "Tech Identity"],
      link: "/projects/web-kitchen",
    },
    {
      id: 3,
      title: "Jedidah: Lifestyle Brand Ops",
      category: "Brand Design",
      image: "/projects/jedidah.webp",
      color: "#b022b0",
      description: "Building a cult-following brand identity through sharp geometric aesthetics and high-end cultural positioning.",
      tags: ["Cultural Positioning", "Design Systems"],
      link: "/projects/jedidah",
    },
  ],
};
